module TargetWizard

include("TargetSelect.jl")
include("TargetSelectXL.jl")
include("TargetBind.jl")
include("report/BasicAquisition.jl")
include("report/TargetSelection.jl")
include("report/TargetAquisition.jl")
include("report/TargetAquisitionXL.jl")
include("report/PeptideCoverage.jl")
include("report/PeptideCoverageXL.jl")
include("report/NoiseRatioDualXL.jl")
include("view/Target.jl")
include("view/TargetXL.jl")
include("view/TargetDualXL.jl")
include("view/CrossLinkSite.jl")
include("view/ExhaustiveSearchXL.jl")

main_TargetSelect()::Cint = TargetSelect.julia_main()
main_TargetSelectXL()::Cint = TargetSelectXL.julia_main()
main_TargetBind()::Cint = TargetBind.julia_main()
main_BasicAquisitionReport()::Cint = BasicAquisitionReport.julia_main()
main_TargetSelectionReport()::Cint = TargetSelectionReport.julia_main()
main_TargetAquisitionReport()::Cint = TargetAquisitionReport.julia_main()
main_TargetAquisitionXLReport()::Cint = TargetAquisitionXLReport.julia_main()
main_PeptideCoverageReport()::Cint = PeptideCoverageReport.julia_main()
main_PeptideCoverageXLReport()::Cint = PeptideCoverageXLReport.julia_main()
main_NoiseRatioDualXLReport()::Cint = NoiseRatioDualXLReport.julia_main()
main_TargetView()::Cint = TargetView.julia_main()
main_TargetXLView()::Cint = TargetXLView.julia_main()
main_TargetDualXLView()::Cint = TargetDualXLView.julia_main()
main_CrossLinkSiteView()::Cint = CrossLinkSiteView.julia_main()
main_ExhaustiveSearchXLView()::Cint = ExhaustiveSearchXLView.julia_main()

end
