module TargetWizard

include("TargetSelect.jl")
include("TargetSelectXL.jl")
include("TargetBind.jl")
include("report/BasicAcquisition.jl")
include("report/TargetSelection.jl")
include("report/TargetAcquisition.jl")
include("report/TargetAcquisitionXL.jl")
include("report/PeptideCoverage.jl")
include("report/PeptideCoverageXL.jl")
include("report/NoiseRatioDualXL.jl")
include("view/Target.jl")
include("view/TargetXL.jl")
include("view/TargetDualXL.jl")
include("view/CrossLinkSite.jl")
include("view/ExhaustiveSearchXL.jl")

main_TargetSelect()::Cint = TargetSelect.julia_main()
main_TargetSelectXL()::Cint = TargetSelectXL.julia_main()
main_TargetBind()::Cint = TargetBind.julia_main()
main_BasicAcquisitionReport()::Cint = BasicAcquisitionReport.julia_main()
main_TargetSelectionReport()::Cint = TargetSelectionReport.julia_main()
main_TargetAcquisitionReport()::Cint = TargetAcquisitionReport.julia_main()
main_TargetAcquisitionXLReport()::Cint = TargetAcquisitionXLReport.julia_main()
main_PeptideCoverageReport()::Cint = PeptideCoverageReport.julia_main()
main_PeptideCoverageXLReport()::Cint = PeptideCoverageXLReport.julia_main()
main_NoiseRatioDualXLReport()::Cint = NoiseRatioDualXLReport.julia_main()
main_TargetView()::Cint = TargetView.julia_main()
main_TargetXLView()::Cint = TargetXLView.julia_main()
main_TargetDualXLView()::Cint = TargetDualXLView.julia_main()
main_CrossLinkSiteView()::Cint = CrossLinkSiteView.julia_main()
main_ExhaustiveSearchXLView()::Cint = ExhaustiveSearchXLView.julia_main()

end
